services:
  dataclips:
    build: ./
    ports:
      - 80:80
    environment:
      REDIS_HOST: redis

      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: dataclips
      DATABASE_USERNAME: dataclips
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SEARCH_ENGINE: "meilisearch"

      MEILISEARCH_HOST: http://meilisearch:7700

  redis:
    image: redis:6
    restart: always

  postgres:
    image: postgres:14
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dataclips
      POSTGRES_USER: dataclips
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

  meilisearch:
    image: getmeili/meilisearch:v0.25.2
    restart: always
    volumes:
      - ./meilisearch/data:/data.ms
