name: Build

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta client
        id: docker-meta-client
        uses: docker/metadata-action@v3
        with:
          images: |
            xudongdev/dataclips-client
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Docker meta server
        id: docker-meta-server
        uses: docker/metadata-action@v3
        with:
          images: |
            xudongdev/dataclips-server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/client
          push: true
          tags: ${{ steps.docker-meta-client.outputs.tags }}
          labels: ${{ steps.docker-meta-client.outputs.labels }}
      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./packages/server
          push: true
          tags: ${{ steps.docker-meta-server.outputs.tags }}
          labels: ${{ steps.docker-meta-server.outputs.labels }}
